export type SchoolFieldKey =
  | "name"
  | "class"
  | "section"
  | "fathersName"
  | "mothersName"
  | "dob"
  | "address"
  | "phone"
  | "rollNo"
  | "admissionNo"
  | "height"
  | "weight"
  | "bloodGroup"
  | "houseName";

export type SchoolFieldType = "text" | "tel" | "date" | "number" | "select";
export type SchoolFieldWidth = "full" | "half" | "third";

export interface SchoolFieldConfig {
  key: SchoolFieldKey;
  required?: boolean;
  width?: SchoolFieldWidth;
  placeholder?: string;
}

export interface SchoolConfig {
  slug: string;
  name: string;
  title: string;
  subtitle: string;
  successTitle?: string;
  successMessage?: string;
  fields: SchoolFieldConfig[];
}

export const BLOOD_GROUP_OPTIONS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"] as const;

export const schoolConfigs: SchoolConfig[] = [
  {
    slug: "uhs-chokad",
    name: "UHS Chokad",
    title: "UHS Chokad ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "UHS Chokad details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "class", width: "half" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "dob", width: "half" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
      { key: "address", width: "full" },
      { key: "rollNo", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "height", width: "third", placeholder: "50 to 300 cm" },
      { key: "weight", width: "third", placeholder: "10 to 200 kg" },
      { key: "bloodGroup", width: "third" },
      { key: "houseName", width: "full" },
    ],
  },
  {
    slug: "modern-public-school",
    name: "Modern Public School",
    title: "Modern Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Modern Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "rollNo", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
      { key: "address", width: "full" },
    ],
  },
  {
    slug: "sanskaar-play-school",
    name: "Sanskaar Play School",
    title: "Sanskaar Play School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Sanskaar Play School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "rollNo", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
      { key: "address", width: "full" },
    ],
  },
  {
    slug: "gokul-public-school",
    name: "Gokul Public School",
    title: "Gokul Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Gokul Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "dob", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "st-francis-academy",
    name: "St. Francis Academy",
    title: "St. Francis Academy ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "St. Francis Academy details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "dob", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "golden-public-school",
    name: "Golden Public School",
    title: "Golden Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Golden Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "rollNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "bloodGroup", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "ddrp-public-school",
    name: "DDRP Public School",
    title: "DDRP Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "DDRP Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "dob", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "children-paradise-school",
    name: "Children Paradise School",
    title: "Children Paradise School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Children Paradise School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "janta-high-school",
    name: "Janta High School",
    title: "Janta High School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Janta High School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "3dd-public-school",
    name: "3DD Public School",
    title: "3DD Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "3DD Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "high-school-dimra",
    name: "High School Dimra",
    title: "High School Dimra ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "High School Dimra details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "jyoti-play-school",
    name: "Jyoti Play School",
    title: "Jyoti Play School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Jyoti Play School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "pits-garden-academy",
    name: "Pits Garden Academy",
    title: "Pits Garden Academy ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Pits Garden Academy details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "gajadhar-public-school",
    name: "Gajadhar Public School",
    title: "Gajadhar Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Gajadhar Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "rollNo", width: "half" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "lord-gautam-vidya-mandir",
    name: "Lord Gautam Vidya Mandir",
    title: "Lord Gautam Vidya Mandir ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Lord Gautam Vidya Mandir details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "uhs-nawadih",
    name: "UHS Nawadih",
    title: "UHS Nawadih ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "UHS Nawadih details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "section", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "om-shanti-sishu-mandir",
    name: "Om Shanti Sishu Mandir",
    title: "Om Shanti Sishu Mandir ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Om Shanti Sishu Mandir details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "kids-garden-school",
    name: "Kids Garden School",
    title: "Kids Garden School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Kids Garden School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "half" },
      { key: "rollNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "aman-vidya-mandir",
    name: "Aman Vidya Mandir",
    title: "Aman Vidya Mandir ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Aman Vidya Mandir details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "chaitanya-international-school",
    name: "Chaitanya International School",
    title: "Chaitanya International School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Chaitanya International School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "section", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "half" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "dp-public-school",
    name: "DP Public School",
    title: "DP Public School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "DP Public School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "srijan-academy",
    name: "Srijan Academy",
    title: "Srijan Academy ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Srijan Academy details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "little-flower-school",
    name: "Little Flower School",
    title: "Little Flower School ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Little Flower School details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "jahanvi-vidya-mandir",
    name: "Jahanvi Vidya Mandir",
    title: "Jahanvi Vidya Mandir ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Jahanvi Vidya Mandir details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
  {
    slug: "kiran-baby-paradise",
    name: "Kiran Baby Paradise",
    title: "Kiran Baby Paradise ID Form",
    subtitle: "Student Registration",
    successTitle: "Submitted!",
    successMessage: "Kiran Baby Paradise details have been saved successfully.",
    fields: [
      { key: "name", required: true, width: "half", placeholder: "Required" },
      { key: "fathersName", width: "half" },
      { key: "mothersName", width: "half" },
      { key: "class", width: "third" },
      { key: "rollNo", width: "third" },
      { key: "admissionNo", width: "third" },
      { key: "dob", width: "half" },
      { key: "address", width: "full" },
      { key: "phone", required: true, width: "half", placeholder: "Enter 10 digit phone" },
    ],
  },
];

export function getSchoolConfig(slug: string) {
  return schoolConfigs.find((school) => school.slug === slug);
}

export function getEnabledFieldMap(school: SchoolConfig) {
  return new Map(school.fields.map((field) => [field.key, field]));
}
